import { initializeApp, deleteApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut as secondarySignOut } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
const SC = window.SC || (window.SC = {});
const safe=v=>String(v??"").replace(/[<>&]/g,s=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[s]));
const today=()=>new Date().toISOString().slice(0,10);
const normPw=p=>{p=String(p||"").trim();return p.length>=6?p:(p.padEnd(6,"0")||"000000")};
async function createStudentAuth(id,pw){const app=initializeApp(window.SCFB_CONFIG,"studentCreate_"+Date.now()),auth=getAuth(app),email=SC.studentIdToEmail(id),pass=normPw(pw);try{const cred=await createUserWithEmailAndPassword(auth,email,pass);await secondarySignOut(auth);await deleteApp(app);return{uid:cred.user.uid,email,password:pass}}catch(e){if(e.code==="auth/email-already-in-use"){const cred=await signInWithEmailAndPassword(auth,email,pass);await secondarySignOut(auth);await deleteApp(app);return{uid:cred.user.uid,email,password:pass}}try{await deleteApp(app)}catch(_){}throw e}}
SC.getAllStudentsAndLogs=async function(){const{db,collection,getDocs,query,where}=window.SCFB;const qs=query(collection(db,"users"),where("role","==","student"));const ss=await getDocs(qs);const students=[];ss.forEach(d=>students.push({uid:d.id,...d.data()}));const ls=await getDocs(collection(db,"studyLogs"));const logs=[];ls.forEach(d=>logs.push({id:d.id,...d.data()}));return{students,logs}};
SC.renderTeacherDashboard=async function(){document.getElementById("app").innerHTML=`<section class="card"><h1>👨‍🏫 先生ダッシュボード</h1><div class="actions"><button class="btn primary" onclick="SC.renderAddStudentPage()">＋ 生徒追加</button><button class="btn navy" onclick="SC.loadStudents()">生徒一覧</button><button class="btn navy" onclick="SC.renderTeacherRanking()">ランキング</button></div><div id="teacherBox" class="box">読み込み中...</div><div id="studentsList"></div></section>`;await SC.renderTeacherSummary();await SC.loadStudents()};
SC.renderTeacherSummary=async function(){const box=document.getElementById("teacherBox");try{const{students,logs}=await SC.getAllStudentsAndLogs();const t=today(),m=t.slice(0,7);const active=new Set(logs.filter(l=>l.date===t).map(l=>l.uid)).size;const month=logs.filter(l=>String(l.date||"").startsWith(m)).reduce((s,l)=>s+Number(l.minutes||0),0);box.innerHTML=`<h2>📊 全体サマリー</h2><div class="grid two"><div class="box"><b>登録生徒</b><br>${students.length}名</div><div class="box"><b>今日記録あり</b><br>${active}名</div><div class="box"><b>今日未記録</b><br>${Math.max(0,students.length-active)}名</div><div class="box"><b>今月合計</b><br>${month}分</div></div>`}catch(e){box.innerHTML="読み込めませんでした";console.error(e)}};
SC.renderAddStudentPage=async function(){document.getElementById("app").innerHTML=`<section class="card"><h1>＋ 生徒追加</h1><div id="teacherBox" class="box"></div><div id="studentsList"></div></section>`;await SC.renderAddStudent()};
SC.makeStudentId=async function(){const{students}=await SC.getAllStudentsAndLogs();return"KYOWA"+String(students.length+1).padStart(3,"0")};
SC.renderAddStudent=async function(){let id="KYOWA001";try{id=await SC.makeStudentId()}catch(e){}const pw=String(Math.floor(100000+Math.random()*900000));document.getElementById("teacherBox").innerHTML=`<label>生徒ID</label><input id="newStudentId" value="${id}"><label>初期パスワード</label><input id="newStudentPassword" value="${pw}"><label>氏名</label><input id="newStudentName"><label>学校</label><input id="newStudentSchool"><label>学年</label><input id="newStudentGrade"><label>志望校</label><input id="newStudentTarget"><button class="btn primary" onclick="SC.createStudent()">登録</button><p id="createStudentMsg" class="help"></p>`};
SC.createStudent=async function(){const id=document.getElementById("newStudentId").value.trim(),pw=document.getElementById("newStudentPassword").value.trim(),name=document.getElementById("newStudentName").value.trim();const msg=document.getElementById("createStudentMsg");try{msg.textContent="登録中...";const c=await createStudentAuth(id,pw);const{db,doc,setDoc,serverTimestamp}=window.SCFB;const data={role:"student",studentId:id,email:c.email,initialPassword:c.password,name,school:document.getElementById("newStudentSchool").value,grade:document.getElementById("newStudentGrade").value,targetUniversity:document.getElementById("newStudentTarget").value,authEnabled:true,createdAt:serverTimestamp()};await setDoc(doc(db,"users",c.uid),data,{merge:true});await setDoc(doc(db,"students",c.uid),data,{merge:true});msg.innerHTML=`登録しました。<br>生徒ID：<b>${id}</b><br>PW：<b>${c.password}</b>`}catch(e){msg.textContent="登録できませんでした。";console.error(e)}};
SC.loadStudents=async function(){const list=document.getElementById("studentsList");if(!list)return;const{students}=await SC.getAllStudentsAndLogs();list.innerHTML=students.length?students.map(s=>`<div class="box"><h2>${safe(s.name||"名前未設定")}</h2><p>生徒ID：${safe(s.studentId||"-")}<br>学校：${safe(s.school||"-")} / 学年：${safe(s.grade||"-")}<br>第一志望：${safe(s.targetUniversity||"-")}<br>試験日：${safe(s.firstExamDate||"-")}</p></div>`).join(""):`<div class="box">まだ生徒がいません。</div>`};
SC.renderTeacherRanking=async function(){document.getElementById("app").innerHTML=`<section class="card"><h1>🏆 ランキング</h1><div id="rankBox" class="box">読み込み中...</div></section>`;const{students,logs}=await SC.getAllStudentsAndLogs();const totals={};logs.forEach(l=>totals[l.uid]=(totals[l.uid]||0)+Number(l.minutes||0));const rows=students.map(s=>({name:s.name||s.studentId||"生徒",min:totals[s.uid]||0})).sort((a,b)=>b.min-a.min);document.getElementById("rankBox").innerHTML=rows.length?rows.map((r,i)=>`<div class="box"><b>${i+1}位 ${safe(r.name)}</b><br>${r.min}分</div>`).join(""):"記録がありません。"};
SC.renderAllTestRecordsForTeacher=async function(){document.getElementById("app").innerHTML=`<section class="card"><h1>🧾 テスト記録</h1><div id="allTestRecordsBox" class="box">読み込み中...</div></section>`;const box=document.getElementById("allTestRecordsBox");try{const{db,collection,getDocs}=window.SCFB;const snap=await getDocs(collection(db,"testRecords"));const rec=[];snap.forEach(d=>rec.push(d.data()));box.innerHTML=rec.length?rec.map(r=>`<div class="box"><b>${safe(r.studentName||r.studentId||"生徒")}</b><br>${safe(r.testDate||"")} ${safe(r.testName||r.type||"")}<br>英:${r.scores?.english||"-"} 数:${r.scores?.math||"-"} 国:${r.scores?.japanese||"-"}<br>偏差値:${r.deviation||"-"} 判定:${safe(r.judgement||"-")}</div>`).join(""):"まだ記録がありません。"}catch(e){box.innerHTML="読み込めませんでした";console.error(e)}};
